{application,test_math,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{test_math_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[test_math_app,test_math_server,test_math_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
